API/urls.py
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from rest_framework_swagger.views import get_swagger_view

app_name = 'api'
urlpatterns = [
    # ex: /admin/
    path('manage/', views.ManageIndex, name='manage-index'),
    path('manage/events/', views.ManageEvents, name='manage-events'),
    path('manage/events/<int:event_id>/', views.EventDetail, name='event-detail'),
    path('manage/events/<int:event_id>/update/', views.EventUpdate, name='event-update'),
    path('manage/users/', views.ManageUsers, name='manage-users'),
    path('manage/users/<int:user_id>/', views.UserDetail, name='user-detail'),
    path('manage/users/<int:user_id>/update/', views.UserUpdate, name='user-update'),
    path('manage/users/<int:user_id>/message/', views.CreateNotif, name='notif-create'),
    path('manage/users/<int:user_id>/message/send', views.SendNotif, name='notif-send'),
    path('api/', get_swagger_view(title="EventFinder API")),
    path('api/test/', views.TestAPIView.as_view(), name='test-api'),
    path('api/userlist/', views.ListUsers.as_view(), name='list-users'),
    path('api/createuser/', views.CreateUser.as_view(), name='create-user'),
    path('api/getmyinfo/', views.GetMyInfo.as_view(), name='get-my-info'),
    path('api/activateuser/', views.ActivateUser.as_view(), name='activate-user'),
    path('api/getpastevents/', views.GetPastEvents.as_view(), name='get-past-events'),
    path('api/getfutureevents/', views.GetFutureEvents.as_view(), name='get-future-events'),
    path('api/getmyevents/', views.GetMyEvents.as_view(), name='get-my-events'),
    path('api/personslist/', views.ListPersons.as_view(), name='list-persons'),
    path('api/createpersonaccount/', views.CreatePersonAccount.as_view(), name='create-person-account'),
    path('api/updatepersonaccount/', views.UpdatePersonAccount.as_view(), name='update-person-account'),
	path('api/setprofilepicture/', views.SetProfilePicture.as_view(), name='set-profile-picture'),
    path('api/updatepassword/', views.UpdatePassword.as_view(), name='update-password'),
    path('api/updateevent/', views.UpdateEvent.as_view(), name='update-event'),
    path('api/rsvplist/', views.GetRsvpList.as_view(), name='get-rsvps'),
    path('api/creatersvp/', views.CreateRsvp.as_view(), name='create-rsvp'),
    path('api/updatersvp/', views.UpdateRsvp.as_view(), name='update-rsvp'),
	path('api/sendreport/', views.SendReport.as_view(), name='send-report'),
	path('api/token/login/', obtain_jwt_token),
    path('api/token/validate/', verify_jwt_token),
    path('api/token/refresh/', refresh_jwt_token),
    path('api/weblogin/', include('rest_framework.urls')),
    path('api/getperson/<int:id>/', views.GetPerson.as_view(), name='get-person-by-id'),
    path('api/createevent/', views.CreateEvent.as_view(), name='create-event'),
    path('api/getrecentevents/<int:count>/', views.GetRecentEvents.as_view(), name='getrecentevents'),
	path('api/getnotifications/', views.GetNotifications.as_view(), name='getnotifications'),
	path('api/createconversation/', views.CreateConversation.as_view(), name='create-coversation'),
	path('api/createmessage/', views.CreateChatMessage.as_view(), name='create-chat-message')
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EventFinder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
	path('admin/', admin.site.urls),
	url(r'^', include('API.urls'))
]

API/models/Person.py
from django.contrib.auth.models import User
from django.db import models

#=======================================================
#
#	Model to be used for the account of a user
#	which is and individual person. This will be
#	the default account model. 
#
#=======================================================

class Person(models.Model):

	#
	# The User this Person Account belongs to:
	user = models.OneToOneField(User)
	
	#
	# Personal Account Attributes:
	date_of_birth = models.DateField()
	bio = models.CharField(max_length=500)
	primaryLocation = models.CharField(max_length=200) #todo: Needs to be a Location, not just text
	currentLocation = models.CharField(max_lenght=200) #todo: Needs to be a Location, not just text
	hideLocation = models.BooleanField(default=False)

	  #todo: profilePicture ImageField
          #todo: photos array[images]
	  #todo: interests... I believe that this needs to be implemented from the interests model..
	  #	  as in, an interest will belong to many users. Then from this model a getInterests()
	  #	  function can be implemented.

API/models/conversation.py
from django.db import models
from django.contrib.auth.models import User
from .event import Event

class Conversation(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	host = models.ForeignKey(User, on_delete=models.CASCADE,related_name="host_account")
	guest = models.ForeignKey(User, on_delete=models.CASCADE,related_name="guest_account")

API/models/event.py
from django.db import models
from django.contrib.auth.models import User
from .interest import Interest

class Event(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	event_name = models.CharField(max_length=100)
	location = models.CharField(max_length=200)
	event_date = models.DateTimeField()
	description = models.CharField(max_length=512)
	age_min = models.IntegerField(default=0)
	age_max = models.IntegerField(default=0)
	interests = models.CharField(max_length=200, default = '')
	attendees = models.ManyToManyField(User, related_name="attendee_accounts")
	host = models.ForeignKey(User, on_delete=models.CASCADE, related_name="event_host_account")
	is_hidden = models.BooleanField(default=False)

API/models/eventpicture.py
from django.db import models
from API.models import Event

class EventPicture (models.Model):
	event = models.OneToOneField(Event, on_delete=models.CASCADE)
	image = models.FileField(null=True, blank=True)

API/models/interest.py
from django.db import models

class Interest(models.Model):
	name = models.CharField(max_length=512)

API/models/interests.py
from django.db import models

class Interests(models.Model):
	name = models.CharField(max_length=100)
	haveIt = models.BooleanField(default=False)

API/models/message.py
from django.db import models
from django.contrib.auth.models import User
from .conversation import Conversation

class Message(models.Model):
	date_sent = models.DateTimeField(auto_now_add=True)
	conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
	sender = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.CharField(max_length=512)

API/models/notification.py
from django.db import models
from .event import Event
from .rsvp import Rsvp
from django.contrib.auth.models import User
from datetime import datetime

class Notification(models.Model):
	DEFAULT_ID = 1
	sender = models.ForeignKey(User, on_delete=models.CASCADE, default=DEFAULT_ID, related_name='sender')
	receiver = models.ForeignKey(User, on_delete=models.CASCADE, default=DEFAULT_ID, related_name='receiver') #was previously reciver
	date_created = models.DateTimeField(default=datetime.now, blank=True)
	date_sent = models.DateTimeField(null=True)
	message = models.CharField(max_length=512)
 

API/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class NotificationForm(forms.Form):
	sender = forms.CharField()
	username = forms.CharField()
	reciver = forms.CharField()
	message = forms.CharField(max_length=512)

API/views.py
from django.shortcuts import render
from rest_framework.views import APIView	# class based views
from rest_framework.decorators import api_view	# function based views
from API.models import Person
from API.models import ProfilePicture
from API.models import Event
from API.models import Report
from API.models import Rsvp
from API.models import Notification
from API.models import Conversation
from API.models import Message
from django.contrib.auth.models import User
from .serializers import PersonSerializer
from .serializers import PictureSerializer
from .serializers import UserSerializer
from .serializers import EventSerializer
from .serializers import UpdatePasswordSerializer
from .serializers import ReportSerializer
from .serializers import RsvpSerializer
from .serializers import NotificationSerializer
from .serializers import MessageSerializer
from .serializers import ConversationSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from rest_framework.decorators import authentication_classes, permission_classes
import datetime # dont remove needed to import this way for the datetime.date.today()

from django.shortcuts import get_object_or_404, render
from django.db.models import Count, Q
from django.http import HttpResponseRedirect, HttpResponse
import os
import json
from .forms import NotificationForm
from django.conf import settings

#########################
# Start Manage Views
#########################
def ManageIndex(request):
	event_list = Event.objects.filter(is_hidden=False).annotate(report_count=Count('report',filter=Q(id__in=Report.objects.all()))).filter(report_count__gt=0).order_by('-report_count')[:5]
	user_list = User.objects.filter(person__isBanned=False).annotate(report_count=Count('reported_account', filter=Q(id__in=Report.objects.all()))).filter(report_count__gt=0)[:5]
	context = {'event_list': event_list, 'user_list': user_list}
	return render(request, 'API/manage_home.html', context)

def ManageEvents(request):
	event_list = Event.objects.annotate(report_count=Count('report',filter=Q(id__in=Report.objects.all()))).filter(report_count__gt=0)[:10]
	context={'event_list': event_list}
	return render(request, 'API/manage_events.html', context)

def ManageUsers(request):
	user_list = User.objects.annotate(report_count=Count('reported_account', filter=Q(id__in=Report.objects.all()))).filter(report_count__gt=0)
	context = {'user_list': user_list}
	return render(request, 'API/manage_users.html', context)

def EventDetail(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	report_list = Report.objects.filter(rep_event=event_id)
	context={'event': event, 'report_list': report_list}
	return render(request, 'API/manage_event_detail.html', context)

def UserDetail(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	report_list = Report.objects.filter(rep_account=user_id)
	context={'user': user, 'report_list': report_list}
	return render(request, 'API/manage_user_detail.html', context)

def EventUpdate(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	event.is_hidden = not event.is_hidden
	event.save()
	return HttpResponseRedirect('/manage/events/' + str(event_id))

def UserUpdate(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	user.person.isBanned = not user.person.isBanned
	user.person.save()
	return HttpResponseRedirect('/manage/users/' + str(user_id))

def CreateNotif(request, user_id):
	user = User.objects.get(pk=user_id)
	context = {'user': user}
	return render(request, 'API/manage_message_user.html', context)

def SendNotif(request, user_id):
	if request.method == 'POST':
		form = NotificationForm(request.POST)

		if form.is_valid():
			#proccess here
			sender = User.objects.get(pk=form.cleaned_data['sender'])
			reciver = User.objects.get(pk=form.cleaned_data['reciver'])
			message = form.cleaned_data['message']

			notif = Notification.objects.create(
				sender=sender,
				reciver=reciver,
				message=message)
			notif.save()

			return HttpResponseRedirect('/manage/users/' + str(user_id))
	return HttpResponseRedirect('/manage/users/' + str(user_id) + '/message/')

#class TempResult(APIView):
#	def get(self, request, format='json'):
#		BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#		return Response(BASE_DIR)
#########################
# End Manage Views
#########################

@permission_classes([])
class GetRsvpList(APIView):
	# get list of Rsvps
	def get(self, request, format='json'):
		rsvps = Rsvp.objects.all()
		serializer = RsvpSerializer(rsvps, many=True)
		return Response(serializer.data)

class SendReport(APIView):
	def post(self, request, format='json'):
		request.data['snitch'] = request.user.id
		s = ReportSerializer(data=request.data)
		if s.is_valid():
			s.save()
			return Response(s.data, status=status.HTTP_201_CREATED)
		else:
			return Response(s.errors, status=status.HTTP_400_BAD_REQUEST)

# EX:
# {
# 	"event": 1,
# 	"requester": 3
# }
@permission_classes([])
class CreateRsvp(APIView):
	# when a RSVP is created
	def post(self, request, format='json'):
		serializer = RsvpSerializer(data=request.data)
		if serializer.is_valid():
			rsvp = serializer.save()
			if rsvp:
				# rsvp's are now going to be the notificication not a seperate notification
				# create a notification for the host accept/decline
				#notif = Notification.objects.create(
				#	rsvp=rsvp,
				#	sender=User.objects.get(pk=rsvp.requester.id),
				#	reciver=User.objects.get(pk=rsvp.event.host.id),
				#	message=rsvp.requester.username + " has requested to join your event: " + rsvp.event.event_name
				#	)
				#notif.save()
				return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# EX:
# {
# 	"id": 1,
# 	"status": 1
# }
@permission_classes([])
class UpdateRsvp(APIView):
	def patch(self, request, format='json'):
		rsvp_id = request.data.get("id")
		rsvp = Rsvp.objects.get(pk=rsvp_id)
		serializer = RsvpSerializer(rsvp,data=request.data, partial=True)
		if serializer.is_valid():
			rsvp = serializer.save()
			if rsvp:
			# create notification for the requester that details the descision
				return Response(serializer.data, status=status.HTTP_200_OK)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#
# To test api
@permission_classes([])
class TestAPIView(APIView):
	def get(self, request, format='json'):
		username = 'stranger' if not request.user.username else request.user.username
		return Response("Hi %s! Welcome to the API!!" % username)

#
# api end point to list all users...
class ListUsers(APIView):
	def get(self, request, format='json'):
		users = User.objects.all()
		serializer = UserSerializer(users, many=True)
		return Response(serializer.data)

'''
 api end point to create a user (without account)...
 to create user send data in following json format via post...
 {"username": "taylor789", "email": "example@ex.com", "password":"iwejfoiwejfdk"}
'''
@permission_classes([])
class CreateUser(APIView):
	def post(self, request, format='json'):
		serializer = UserSerializer(data=request.data)
		if serializer.is_valid():
			user = serializer.save()
			if user:
				return Response(serializer.data, status=status.HTTP_201_CREATED)

'''
 Note: when calling ActivateUser in the future we will need to check whether 
		the account is a person or business account type. If this were a 
		business account being activated, u.person would not exist as the
		account type for the user would be a business account. For now it's 
		fine since there is only one account type that can belong to a user.
'''
@permission_classes([])
class ActivateUser(APIView):
	def get(self, request, format='none'):
		u = User.objects.get(id=request.GET.get('id'))
		if u.person.isBanned:
			return Response("Error: This user has been banned.")
		if u.is_active:
			return Response("Error: This user is already confirmed.")
		else:
			g = PasswordResetTokenGenerator()
			if g.check_token(u, request.GET.get('token')):
				u.is_active = True
				u.last_login = datetime.datetime.now() # We need to change something to invalidate the token.
				u.save()
				return Response("Success.  The account for %s is now active!" % (u.username))
			else:
				return Response("Error: This token appears to be old or invalid.")

'''
	End point for getting Person Account info from Person 'id'
		JSON fields expected:

'''

class GetPerson(APIView):
	def get(self, request, id, format='none'):
		try:
			p = Person.objects.get(pk=id)
			serializer = PersonSerializer(p)
			return Response(serializer.data, status=status.HTTP_200_OK)
		except Person.DoesNotExist:
			return Response("Person id does not exist.", status=status.HTTP_400_BAD_REQUEST)

'''
	Update User Password Endpoint
		JSON fields expected:
			"id" (user object id)
			"old_password"
			"new_password"
'''
class UpdatePassword(APIView):
	def put(self, request, format='json'):
		serialized = UpdatePasswordSerializer(data=request.data)
		if serialized.is_valid():
			try:
				user = User.objects.get(id=serialized.data.get("id"))
				if not user.check_password(serialized.data.get("old_password")):
					return Response({"old_password": "Wrong password."}, status=status.HTTP_400_BAD_REQUEST)
				user.set_password(serialized.data.get("new_password"))
				user.save()
				return Response("Success.", status=status.HTTP_200_OK)
			except User.DoesNotExist:
				return Response("User id does not exist.", status=status.HTTP_404_NOT_FOUND)
		return Response(serialized.errors, status=status.HTTP_400_BAD_REQUEST)

class GetMyInfo(APIView):
	'''
	'''
	def get(self, request, format='json'):
		if request.user:
			try:
				p = Person.objects.get(user=request.user)
				serializer = PersonSerializer(p)
				return Response(serializer.data, status=status.HTTP_200_OK)

API/templates/API/manage_event_detail.html
{% load static %}

<head>
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'API/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'API/style.css' %}">
    <script src="{% static 'API/js/custom.js' %}"></script>
</head>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Event Finder</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/manage/">Home</a></li>
      <li class="active"><a href="/manage/events/">Events</a></li>
      <li><a href="/manage/users/">Users</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1>Event Info</h1>
	{% if event %}
    <!-- Event Info -->
		<label for="event_id">EventID:</label>
    <input type="text" class="form-control" id="event_id" placeholder="" value="{{ event.id }}" name="event_id" disabled="disabled">

		<label for="event_name">Event Name:</label>
    <input type="text" class="form-control" id="event_name" placeholder="" value="{{ event.event_name }}" name="event_name" disabled="disabled">

    <label for="event_desc">Description:</label>
    <input type="text" class="form-control" id="event_desc" placeholder="" value="{{ event.description }}" name="event_desc" disabled="disabled">

    <label for="event_location">Location:</label>
    <input type="text" class="form-control" id="event_location" placeholder="" value="{{ event.location }}" name="event_location" disabled="disabled">

    <label for="event_date">Event Date:</label>
    <input type="text" class="form-control" id="event_date" placeholder="" value="{{ event.event_date }}" name="event_date" disabled="disabled">

    <label for="event_age_min">Age Min:</label>
    <input type="text" class="form-control" id="event_age_min" placeholder="" value="{{ event.age_min }}" name="event_age_min" disabled="disabled">

    <label for="event_age_max">Age Max:</label>
    <input type="text" class="form-control" id="event_age_max" placeholder="" value="{{ event.age_max }}" name="event_age_max" disabled="disabled">

    <label for="event_date_created">Date Created:</label>
    <input type="text" class="form-control" id="event_date_created" placeholder="" value="{{ event.date_created }}" name="event_date_created" disabled="disabled">

    <div class="checkbox">
      <label><input type="checkbox" id="hidden" name="hidden" value="" {% if event.is_hidden %} checked {% endif %} disabled="disabled">Is Hidden:</label>
    </div>
    <!-- End Event Info -->

    <div class="row pull-right">
      <button type="button" class="btn btn-primary" onclick="messageUser({{ event.host.id }})">Message Host</button>
      <button type="button" class="btn btn-danger" onclick="updateEvent()">Hide Event</button>
    </div>

    <div class="row">
	    <div class="col-lg-12">
		    <h2>Reports</h2>
		    <table class="table table-striped">
		    	<thead>
		    		<tr>
		    			<th>Reportee</th>
		    			<th>Report Text</th>
		    			<th>Date Submitted</th>
		    		</tr>
		    	</thead>
          {% for report in report_list %}
          <tr>
            <td>{{ report.snitch.username }}</td>
            <td>{{ report.rep_message }}</td>
            <td>{{ report.date_created }}</td>
          </tr>
          {% endfor%}
		    </table>
	    </div> <!-- end col-lg-12 -->
		</div> <!-- end row -->
  {% else %}
    	<p>No event exists with that id!</p>
  {% endif %}
</div> <!-- end container -->

API/templates/API/manage_events.html
{% load static %}

<head>
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'API/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'API/style.css' %}">
    <script src="{% static 'API/js/custom.js' %}"></script>
</head>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Event Finder</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/manage/">Home</a></li>
      <li class="active"><a>Events</a></li>
      <li><a href="/manage/users/">Users</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
    </ul>
  </div>
</nav>

<div class="container">
	<div class="row">
		<h3>Reported Events</h3>
		<div class="table-responsive">
	  		<table class="table">
	  			<tr>
	  				<th>ID</th>
	  				<th>Name</th>
	  				<th>Event Date</th>
	  				<th>Host</th>
	  				<th>Report Count</th>
	  				<th>Is Hidden</th>
	  				<th>Manage</th>
	  			</tr>
	  			{% for event in event_list %}
	  			<tr>
	  				<td>{{ event.id }}</td>
	  				<td>{{ event.event_name }}</td>
	  				<td>{{ event.event_date }}</td>
	  				<td>{{ event.host }}</td>
	  				<td>{{ event.report_count }}</td>
	  				<td>{{ event.is_hidden }}</td>
	  				<td><button type="button" class="btn btn-primary" onclick="manageEvent({{ event.id }})">Manage</button></td>
	  			</tr>
	  			{% endfor %}
	  		</table>
  		</div> <!-- end "table-responsive"-->
	</div> <!-- end "row" -->
</div> <!-- end "container" -->

API/templates/API/manage_home.html
{% load static %}

<head>
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'API/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'API/style.css' %}">
    <script src="{% static 'API/js/custom.js' %}"></script>
</head>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Event Finder</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a>Home</a></li>
      <li><a href="/manage/events/">Events</a></li>
      <li><a href="/manage/users/">Users</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <span>TODO:</span>
  <ul>
    <li>check with report functionality to determine if user or person id is reported</li>
    <li></li>
    <li></li>
  </ul>
</div>
  
<div class="container">
  <div class="row">
    <h2>Highest Reported Events</h2>
    <div class="table-responsive">
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Event Date</th>
            <th>Host</th>
            <th>Report Count</th>
            <th>Manage</th>
          </tr>
          {% for event in event_list %}
          <tr>
            <td>{{ event.id }}</td>
            <td>{{ event.event_name }}</td>
            <td>{{ event.event_date }}</td>
            <td>{{ event.host }}</td>
            <td>{{ event.report_count }}</td><td><button type="button" class="btn btn-primary" onclick="manageEvent({{ event.id }})">Manage</button></td>
          </tr>
          {% endfor %}
        </table>
      </div> <!-- end "table-responsive"-->
  </div> <!-- end "row" -->

  <div class="row">
    <h2>Highest Reported Users</h2>
    <div class="table-responsive">
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Report Count</th>
            <th>Manage</th>
          </tr>
          {% for user in user_list %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.report_count }}</td>
            <td><button type="button" class="btn btn-primary" onclick="manageUser({{ user.id }})">Manage</button></td>
          </tr>
          {% endfor %}
        </table>
      </div> <!-- end "table-responsive"-->
  </div> <!-- end "row" -->
</div> <!-- end "container" -->

API/templates/API/manage_message_user.html
{% load static %}

<head>
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'API/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'API/style.css' %}">
    <script src="{% static 'API/js/custom.js' %}"></script>
</head>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Event Finder</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/manage/">Home</a></li>
      <li><a href="/manage/events/">Events</a></li>
      <li><a href="/manage/users/">Users</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1>Message User</h1>
  <form action="{% url 'api:notif-send' user.id %}" method="post">
    {% csrf_token %}
		<!--label for="reciever">UserID:</label>
    <input type="text" class="form-control" id="reciever" placeholder="" value="{{ user.id }}" name="reciever" disabled="disabled">

		<label for="username">Username:</label>
    <input type="text" class="form-control" id="username" placeholder="" value="{{ user.username }}" name="username" disabled="disabled">

    <label for="message">Message:</label>
    <input type="text" class="form-control" id="message" placeholder="" name="message" >

    <input type="hidden" id="sender" name="sender" value="1"-->

<input type="hidden" class="form-control" name="sender" value="1"  id="id_sender" required />


<label for="id_reciver">Recipient ID:</label>
<input type="text" class="form-control" name="reciver" value="{{ user.id }}" id="id_reciver" readonly required />

<label for="id_username">Username:</label>
<input type="text" class="form-control" name="username" value="{{ user.username }}" id="id_username" readonly required />

<label for="id_message">Message:</label>
<input type="text" class="form-control" name="message" id="id_message" maxlength="512" required />

    <div class="row pull-right">
      <button type="submit" class="btn btn-primary">Send</button>
    </div>
  </form>

</div> <!-- end container -->